### ISSUE TITLE
Do I need to install Photon on playfab.com?

### ISSUE THREAD

**Issue by Whiskah** [insthync/shooter-io-playfab-client-demo#2]
Do I actually need to install this on playfab aswell? Or is this just used for storing currency/heads/google login information?
![image](https://user-images.githubusercontent.com/27635588/125864219-a68dcb7d-360a-4c64-8a32-3bf63e98b6e3.png)

**Comment by insthync** [comment]
No, you don't have to setup Photon in Playfab dashboard.

**Comment by Whiskah** [comment]
Awesome thanks
