### ISSUE TITLE
Memory Leak Error

### ISSUE THREAD

**Issue by Safewaygames** [insthync/shooter-io-playfab-client-demo#5]
So at first I thought it was something I did but in a fresh project I keep getting an error about A native collection has not been disposed resulting in a memory leak
![memory leak](https://user-images.githubusercontent.com/71611113/181279876-ee4b071b-4b24-47e8-b7c8-78db310d8ff1.png)

Also when using Shooter IO playfab client gold rewards are not being applied after the fight when using playfab. but when not using playfab gold rewards are good working just fine. I have a video showing that after a match gold is not rewarded but if not using playfab gold is rewarded just fine.
https://youtu.be/N135YkLxeGU

**Comment by insthync** [comment]
Please enable full stack traces to get more details

**Comment by Safewaygames** [comment]
I did enable full stack traces and just give me that same error many times over did not give me any useful information.

**Comment by Safewaygames** [comment]
Its was Playfab Editor
