### ISSUE TITLE
Unity Ads Update

### ISSUE THREAD

**Issue by Safewaygames** [insthync/shooter-io-playfab-client-demo#6]
They way unity Ads is Implemented no longer works and is not usable anymore on any store it is getting our app removed. Could you take a look at it and update it so that we are able to use unity ads 4.2.1 which is now the needed version.
![update ads](https://user-images.githubusercontent.com/71611113/181810912-219c4ab5-33c2-46cb-a618-fb16dcbb7586.png)
This is the error we get when updating unity ads in the project to be compliant with IOS and Android app stores.

**Comment by insthync** [comment]
Updated
